import { Course } from '@/types';

export const lecturerCourses: Course[] = [
  {
    id: '1',
    code: 'CS101',
    name: 'Intro to Algorithm',
    level: 'Level 100',
    module: 'Core Module',
    enrollment: 124,
    enrollmentTrend: '+4%',
    trendType: 'positive',
    classRep: 'Jane Smith',
    classRepInitials: 'JS',
    performance: 78,
    icon: 'code',
  },
  {
    id: '2',
    code: 'DB105',
    name: 'Relational Systems',
    level: 'Level 200',
    module: 'Elective Module',
    enrollment: 86,
    enrollmentTrend: 'Stable',
    trendType: 'neutral',
    classRep: 'Alex Miller',
    classRepInitials: 'AM',
    performance: 92,
    icon: 'database',
  },
  {
    id: '3',
    code: 'AL302',
    name: 'AI Ethics',
    level: 'Level 300',
    module: 'Advanced Module',
    enrollment: 45,
    enrollmentTrend: '-2%',
    trendType: 'negative',
    classRep: 'Lina Khan',
    classRepInitials: 'LK',
    performance: 61,
    icon: 'brain',
  },
  {
    id: '4',
    code: 'DS204',
    name: 'Data Structures',
    level: 'Level 200',
    module: 'Core Module',
    enrollment: 102,
    enrollmentTrend: '+1%',
    trendType: 'positive',
    classRep: 'Ruth Owen',
    classRepInitials: 'RO',
    performance: 84,
    icon: 'book',
  },
];

export const performanceData = [
  { course: 'CS101', value: 85, fill: '#0f1e5a' },
  { course: 'DS204', value: 75, fill: '#f5a623' },
  { course: 'AL302', value: 90, fill: '#0f1e5a' },
  { course: 'DB105', value: 80, fill: '#0f1e5a' },
];
